---
- hosts: grid
  tasks:
          - name: Delete content & directory
            file:
                  state: absent
                  path: "/homes/{{ hostvars[inventory_hostname].ansible_user }}/run_models_distributed"
          - debug:
                  msg: "/homes/{{ hostvars[inventory_hostname].ansible_user }}/run_models_distributed"
          - name: Clone a git repository
            git:
                    repo: https://github.com/luisroque/run_models_distributed.git
                    dest: "/homes/{{ hostvars[inventory_hostname].ansible_user }}/run_models_distributed"
                    clone: yes
                    update: yes
          - name: Add path and initialize conda
            shell: export PATH=~/anaconda3/bin:$PATH && conda init
            args:
                    executable: /bin/bash
          - name: Conda create new env
            shell: |
                   source "/homes/{{ hostvars[inventory_hostname].ansible_user }}/anaconda3/bin/activate"
                   conda activate run_models
                   pip install -r "/homes/{{ hostvars[inventory_hostname].ansible_user }}/run_models_distributed/requirements.txt"
            args:
                    executable: /bin/bash
            register: shell_output
          - debug: var=shell_output.stdout_lines
          - name: Run m5 grid
            shell: |
                   source "/homes/{{ hostvars[inventory_hostname].ansible_user }}/anaconda3/bin/activate"
                   conda activate run_models
                   cd run_models_distributed
                   sbatch -o m5_output run_m5_slurm
            args:
                    executable: /bin/bash
            register: shell_output
          - debug: var=shell_output.stdout_lines
