#!/bin/bash
#SBATCH --ntasks=8   # number of processor cores (i.e. tasks)
#SBATCH --mem-per-cpu=4G   # memory per CPU core
#SBATCH --mail-user=luis_roque@live.com   # email address
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
python run_m5.py
