#!/bin/bash
#SBATCH --time=0:10:00   # walltime
#SBATCH --ntasks=16   # number of processor cores (i.e. tasks)
SBATCH --mem=127G
#SBATCH --nodes=1   # number of nodes
#SBATCH -p batch   # partition(s)
#SBATCH --mem-per-cpu=100M   # memory per CPU core
#SBATCH -J "jbarber"   # job name
#SBATCH --mail-user=your@email.address   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --qos=test
python run_m5.py
