---
- hosts: [servers]
  strategy: free
  tasks:
          - name: Run tourism mint coral
            shell: |
                   source "/home/{{ hostvars[inventory_hostname].ansible_user }}/anaconda3/bin/activate"
                   conda activate run_models
                   cd run_models_distributed
                   python run_models.py -a mint
            args:
                    executable: /bin/bash
            register: shell_output
            when: "'coral' in inventory_hostname"
          - name: Run tourism gpf jitter and scaling
            shell: |
                   source "/home/{{ hostvars[inventory_hostname].ansible_user }}/anaconda3/bin/activate"
                   conda activate run_models
                   cd run_models_distributed
                   python run_models.py -a gpf -t jitter scaling
            args:
                    executable: /bin/bash
            when: "'marineye' in inventory_hostname"
          - name: Run tourism gpf magnitude and time warping
            shell: |
                   source "/home/{{ hostvars[inventory_hostname].ansible_user }}/anaconda3/bin/activate"
                   conda activate run_models
                   cd run_models_distributed
                   python run_models.py -a gpf -t time_warp
            args:
                    executable: /bin/bash
            when: "'nitro' in inventory_hostname"
          - name: Copy result files back to host
            shell: |
                   scp -r /home/lroque/run_models_distributed/results/* mach2ne:/home/mach2ne/run_models_distributed/results
            args:
                    executable: /bin/bash
