---
- hosts: [servers]
  tasks:
          - name: Delete content & directory
            file:
                  state: absent
                  path: "/home/{{ hostvars[inventory_hostname].ansible_user }}/run_models_distributed"
          - debug:
                  msg: "/home/{{ hostvars[inventory_hostname].ansible_user }}/run_models_distributed"
          - name: Clone a git repository
            git:
                    repo: https://github.com/luisroque/run_models_distributed.git
                    dest: "/home/{{ hostvars[inventory_hostname].ansible_user }}/run_models_distributed"
                    clone: yes
                    update: yes
          - name: Add path and initialize conda
            shell: export PATH=~/anaconda3/bin:$PATH && conda init
            args:
                    executable: /bin/bash
          - name: Conda create new env
            shell: |
                   source "/home/{{ hostvars[inventory_hostname].ansible_user }}/anaconda3/bin/activate"
                   conda activate run_models
                   pip install -r "/home/{{ hostvars[inventory_hostname].ansible_user }}/run_models_distributed/requirements.txt"
            args:
                    executable: /bin/bash
            register: shell_output
          - debug: var=shell_output.stdout_lines
